[2021-05-02 09:41:16,965] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: cn_data_ingesation.merge_files 2021-05-02T09:39:07.339256+00:00 [queued]>
[2021-05-02 09:41:16,975] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: cn_data_ingesation.merge_files 2021-05-02T09:39:07.339256+00:00 [queued]>
[2021-05-02 09:41:16,975] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2021-05-02 09:41:16,975] {taskinstance.py:867} INFO - Starting attempt 1 of 2
[2021-05-02 09:41:16,975] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2021-05-02 09:41:16,984] {taskinstance.py:887} INFO - Executing <Task(PythonOperator): merge_files> on 2021-05-02T09:39:07.339256+00:00
[2021-05-02 09:41:16,987] {standard_task_runner.py:53} INFO - Started process 6753 to run task
[2021-05-02 09:41:17,032] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: cn_data_ingesation.merge_files 2021-05-02T09:39:07.339256+00:00 [running]> ip-172-31-21-147.ec2.internal
[2021-05-02 09:41:17,148] {logging_mixin.py:112} WARNING - /home/ubuntu/airflow/dags/cn_data_ing.py:27: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  final=pd.concat(df_list)
[2021-05-02 09:41:17,171] {python_operator.py:114} INFO - Done. Returned value was: None
[2021-05-02 09:41:17,175] {taskinstance.py:1048} INFO - Marking task as SUCCESS.dag_id=cn_data_ingesation, task_id=merge_files, execution_date=20210502T093907, start_date=20210502T094116, end_date=20210502T094117
[2021-05-02 09:41:26,958] {logging_mixin.py:112} INFO - [2021-05-02 09:41:26,957] {local_task_job.py:103} INFO - Task exited with return code 0
